# Generated by Django 5.0 on 2024-04-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='htmlbody',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
