# Generated by Django 5.0 on 2024-04-08 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0002_emails_htmlbody'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emails',
            old_name='analysed',
            new_name='action',
        ),
    ]
