# Generated by Django 5.0 on 2024-03-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0002_alter_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/img_uploads'),
        ),
    ]
