# Generated by Django 5.0 on 2024-04-09 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0003_rename_analysed_emails_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emails',
            old_name='sentondatetime',
            new_name='receivedondate',
        ),
    ]
