# Generated by Django 5.0 on 2024-03-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0003_alter_account_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='aplication/static/img_uploads'),
        ),
    ]
