# Generated by Django 5.0 on 2024-03-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0004_alter_account_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
