# Generated by Django 5.0 on 2024-05-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0004_rename_sentondatetime_emails_receivedondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='category',
            field=models.CharField(default='Safe', max_length=100),
        ),
    ]
