# Generated by Django 5.0 on 2024-03-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0006_alter_account_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='rule_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antispam', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('agressive', 'Agressive')], default='low', max_length=20)),
                ('antiphishing', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('agressive', 'Agressive')], default='low', max_length=20)),
            ],
        ),
    ]
