# Generated by Django 5.0 on 2024-03-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0007_rule_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subejct', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=100)),
                ('sentondatetime', models.TimeField()),
            ],
        ),
    ]
