# Generated by Django 5.0 on 2024-03-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0008_emails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emails',
            old_name='subejct',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='emails',
            name='analysed',
            field=models.IntegerField(default=0),
        ),
    ]
